# Generated by Django 3.0.3 on 2021-04-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1024)),
                ('poster', models.CharField(max_length=50)),
                ('trailer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_app.Genre')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie_app.Movie')),
            ],
        ),
    ]
