# Generated by Django 3.0.3 on 2021-04-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_auto_20210425_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie_genre',
            unique_together={('movie_id', 'genre_id')},
        ),
    ]
