# Generated by Django 3.0.3 on 2021-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20210426_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='movie_name',
        ),
    ]
