# Generated by Django 3.0.3 on 2021-04-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_auto_20210427_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_genre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Genre'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.Movie'),
        ),
    ]
