# Generated by Django 3.2 on 2021-05-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_auto_20210427_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.TextField(max_length=50),
        ),
    ]
